site_name: Zhang Ruize's Blog
theme:
  name: material
  logo: pics/z.jpeg
  favicon: pics/z.jpeg

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

extra:
  generator: false

plugins:
  - search
  - awesome-pages
