site_name: Zrek Blog
theme:
  name: bootstrap386
  logo: assets/z.png
  favicon: assets/z.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

extra:
  generator: false

plugins:
  - search
  - awesome-pages
